// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace av_player_windows {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class AvPlayerHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class SourceType {
  kNetwork = 0,
  kAsset = 1,
  kFile = 2
};


// Generated class from Pigeon that represents data sent in messages.
class VideoSourceMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit VideoSourceMessage(const SourceType& type);

  // Constructs an object setting all fields.
  explicit VideoSourceMessage(
    const SourceType& type,
    const std::string* url,
    const flutter::EncodableMap* headers,
    const std::string* asset_path,
    const std::string* file_path);

  const SourceType& type() const;
  void set_type(const SourceType& value_arg);

  const std::string* url() const;
  void set_url(const std::string_view* value_arg);
  void set_url(std::string_view value_arg);

  const flutter::EncodableMap* headers() const;
  void set_headers(const flutter::EncodableMap* value_arg);
  void set_headers(const flutter::EncodableMap& value_arg);

  const std::string* asset_path() const;
  void set_asset_path(const std::string_view* value_arg);
  void set_asset_path(std::string_view value_arg);

  const std::string* file_path() const;
  void set_file_path(const std::string_view* value_arg);
  void set_file_path(std::string_view value_arg);


 private:
  static VideoSourceMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class AvPlayerHostApi;
  friend class PigeonInternalCodecSerializer;
  SourceType type_;
  std::optional<std::string> url_;
  std::optional<flutter::EncodableMap> headers_;
  std::optional<std::string> asset_path_;
  std::optional<std::string> file_path_;

};


// Generated class from Pigeon that represents data sent in messages.
class MediaMetadataMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  MediaMetadataMessage();

  // Constructs an object setting all fields.
  explicit MediaMetadataMessage(
    const std::string* title,
    const std::string* artist,
    const std::string* album,
    const std::string* artwork_url);

  const std::string* title() const;
  void set_title(const std::string_view* value_arg);
  void set_title(std::string_view value_arg);

  const std::string* artist() const;
  void set_artist(const std::string_view* value_arg);
  void set_artist(std::string_view value_arg);

  const std::string* album() const;
  void set_album(const std::string_view* value_arg);
  void set_album(std::string_view value_arg);

  const std::string* artwork_url() const;
  void set_artwork_url(const std::string_view* value_arg);
  void set_artwork_url(std::string_view value_arg);


 private:
  static MediaMetadataMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class MediaMetadataRequest;
  friend class AvPlayerHostApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> title_;
  std::optional<std::string> artist_;
  std::optional<std::string> album_;
  std::optional<std::string> artwork_url_;

};


// Generated class from Pigeon that represents data sent in messages.
class EnterPipRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit EnterPipRequest(int64_t player_id);

  // Constructs an object setting all fields.
  explicit EnterPipRequest(
    int64_t player_id,
    const double* aspect_ratio);

  int64_t player_id() const;
  void set_player_id(int64_t value_arg);

  const double* aspect_ratio() const;
  void set_aspect_ratio(const double* value_arg);
  void set_aspect_ratio(double value_arg);


 private:
  static EnterPipRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class AvPlayerHostApi;
  friend class PigeonInternalCodecSerializer;
  int64_t player_id_;
  std::optional<double> aspect_ratio_;

};


// Generated class from Pigeon that represents data sent in messages.
class MediaMetadataRequest {
 public:
  // Constructs an object setting all fields.
  explicit MediaMetadataRequest(
    int64_t player_id,
    const MediaMetadataMessage& metadata);

  ~MediaMetadataRequest() = default;
  MediaMetadataRequest(const MediaMetadataRequest& other);
  MediaMetadataRequest& operator=(const MediaMetadataRequest& other);
  MediaMetadataRequest(MediaMetadataRequest&& other) = default;
  MediaMetadataRequest& operator=(MediaMetadataRequest&& other) noexcept = default;
  int64_t player_id() const;
  void set_player_id(int64_t value_arg);

  const MediaMetadataMessage& metadata() const;
  void set_metadata(const MediaMetadataMessage& value_arg);


 private:
  static MediaMetadataRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class AvPlayerHostApi;
  friend class PigeonInternalCodecSerializer;
  int64_t player_id_;
  std::unique_ptr<MediaMetadataMessage> metadata_;

};


// Generated class from Pigeon that represents data sent in messages.
class AbrConfigMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  AbrConfigMessage();

  // Constructs an object setting all fields.
  explicit AbrConfigMessage(
    const int64_t* max_bitrate_bps,
    const int64_t* min_bitrate_bps,
    const int64_t* preferred_max_width,
    const int64_t* preferred_max_height);

  const int64_t* max_bitrate_bps() const;
  void set_max_bitrate_bps(const int64_t* value_arg);
  void set_max_bitrate_bps(int64_t value_arg);

  const int64_t* min_bitrate_bps() const;
  void set_min_bitrate_bps(const int64_t* value_arg);
  void set_min_bitrate_bps(int64_t value_arg);

  const int64_t* preferred_max_width() const;
  void set_preferred_max_width(const int64_t* value_arg);
  void set_preferred_max_width(int64_t value_arg);

  const int64_t* preferred_max_height() const;
  void set_preferred_max_height(const int64_t* value_arg);
  void set_preferred_max_height(int64_t value_arg);


 private:
  static AbrConfigMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class SetAbrConfigRequest;
  friend class AvPlayerHostApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<int64_t> max_bitrate_bps_;
  std::optional<int64_t> min_bitrate_bps_;
  std::optional<int64_t> preferred_max_width_;
  std::optional<int64_t> preferred_max_height_;

};


// Generated class from Pigeon that represents data sent in messages.
class SetAbrConfigRequest {
 public:
  // Constructs an object setting all fields.
  explicit SetAbrConfigRequest(
    int64_t player_id,
    const AbrConfigMessage& config);

  ~SetAbrConfigRequest() = default;
  SetAbrConfigRequest(const SetAbrConfigRequest& other);
  SetAbrConfigRequest& operator=(const SetAbrConfigRequest& other);
  SetAbrConfigRequest(SetAbrConfigRequest&& other) = default;
  SetAbrConfigRequest& operator=(SetAbrConfigRequest&& other) noexcept = default;
  int64_t player_id() const;
  void set_player_id(int64_t value_arg);

  const AbrConfigMessage& config() const;
  void set_config(const AbrConfigMessage& value_arg);


 private:
  static SetAbrConfigRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class AvPlayerHostApi;
  friend class PigeonInternalCodecSerializer;
  int64_t player_id_;
  std::unique_ptr<AbrConfigMessage> config_;

};


// Generated class from Pigeon that represents data sent in messages.
class DecoderInfoMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit DecoderInfoMessage(bool is_hardware_accelerated);

  // Constructs an object setting all fields.
  explicit DecoderInfoMessage(
    bool is_hardware_accelerated,
    const std::string* decoder_name,
    const std::string* codec);

  bool is_hardware_accelerated() const;
  void set_is_hardware_accelerated(bool value_arg);

  const std::string* decoder_name() const;
  void set_decoder_name(const std::string_view* value_arg);
  void set_decoder_name(std::string_view value_arg);

  const std::string* codec() const;
  void set_codec(const std::string_view* value_arg);
  void set_codec(std::string_view value_arg);


 private:
  static DecoderInfoMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class AvPlayerHostApi;
  friend class PigeonInternalCodecSerializer;
  bool is_hardware_accelerated_;
  std::optional<std::string> decoder_name_;
  std::optional<std::string> codec_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class AvPlayerHostApi {
 public:
  AvPlayerHostApi(const AvPlayerHostApi&) = delete;
  AvPlayerHostApi& operator=(const AvPlayerHostApi&) = delete;
  virtual ~AvPlayerHostApi() {}
  virtual void Create(
    const VideoSourceMessage& source,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  virtual void Dispose(
    int64_t player_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void Play(
    int64_t player_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void Pause(
    int64_t player_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SeekTo(
    int64_t player_id,
    int64_t position_ms,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SetPlaybackSpeed(
    int64_t player_id,
    double speed,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SetLooping(
    int64_t player_id,
    bool looping,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SetVolume(
    int64_t player_id,
    double volume,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void IsPipAvailable(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void EnterPip(
    const EnterPipRequest& request,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void ExitPip(
    int64_t player_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SetMediaMetadata(
    const MediaMetadataRequest& request,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SetNotificationEnabled(
    int64_t player_id,
    bool enabled,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SetSystemVolume(
    double volume,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void GetSystemVolume(std::function<void(ErrorOr<double> reply)> result) = 0;
  virtual void SetScreenBrightness(
    double brightness,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void GetScreenBrightness(std::function<void(ErrorOr<double> reply)> result) = 0;
  virtual void SetWakelock(
    bool enabled,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SetAbrConfig(
    const SetAbrConfigRequest& request,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void GetDecoderInfo(
    int64_t player_id,
    std::function<void(ErrorOr<DecoderInfoMessage> reply)> result) = 0;

  // The codec used by AvPlayerHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `AvPlayerHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    AvPlayerHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    AvPlayerHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  AvPlayerHostApi() = default;

};
}  // namespace av_player_windows
#endif  // PIGEON_MESSAGES_G_H_
