// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.flutterplaza.avplayer

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class SourceType(val raw: Int) {
  NETWORK(0),
  ASSET(1),
  FILE(2);

  companion object {
    fun ofRaw(raw: Int): SourceType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoSourceMessage (
  val type: SourceType,
  val url: String? = null,
  val headers: Map<String?, String?>? = null,
  val assetPath: String? = null,
  val filePath: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoSourceMessage {
      val type = pigeonVar_list[0] as SourceType
      val url = pigeonVar_list[1] as String?
      val headers = pigeonVar_list[2] as Map<String?, String?>?
      val assetPath = pigeonVar_list[3] as String?
      val filePath = pigeonVar_list[4] as String?
      return VideoSourceMessage(type, url, headers, assetPath, filePath)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      url,
      headers,
      assetPath,
      filePath,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaMetadataMessage (
  val title: String? = null,
  val artist: String? = null,
  val album: String? = null,
  val artworkUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaMetadataMessage {
      val title = pigeonVar_list[0] as String?
      val artist = pigeonVar_list[1] as String?
      val album = pigeonVar_list[2] as String?
      val artworkUrl = pigeonVar_list[3] as String?
      return MediaMetadataMessage(title, artist, album, artworkUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      artist,
      album,
      artworkUrl,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EnterPipRequest (
  val playerId: Long,
  val aspectRatio: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EnterPipRequest {
      val playerId = pigeonVar_list[0] as Long
      val aspectRatio = pigeonVar_list[1] as Double?
      return EnterPipRequest(playerId, aspectRatio)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      playerId,
      aspectRatio,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaMetadataRequest (
  val playerId: Long,
  val metadata: MediaMetadataMessage
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaMetadataRequest {
      val playerId = pigeonVar_list[0] as Long
      val metadata = pigeonVar_list[1] as MediaMetadataMessage
      return MediaMetadataRequest(playerId, metadata)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      playerId,
      metadata,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AbrConfigMessage (
  val maxBitrateBps: Long? = null,
  val minBitrateBps: Long? = null,
  val preferredMaxWidth: Long? = null,
  val preferredMaxHeight: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AbrConfigMessage {
      val maxBitrateBps = pigeonVar_list[0] as Long?
      val minBitrateBps = pigeonVar_list[1] as Long?
      val preferredMaxWidth = pigeonVar_list[2] as Long?
      val preferredMaxHeight = pigeonVar_list[3] as Long?
      return AbrConfigMessage(maxBitrateBps, minBitrateBps, preferredMaxWidth, preferredMaxHeight)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      maxBitrateBps,
      minBitrateBps,
      preferredMaxWidth,
      preferredMaxHeight,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SetAbrConfigRequest (
  val playerId: Long,
  val config: AbrConfigMessage
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SetAbrConfigRequest {
      val playerId = pigeonVar_list[0] as Long
      val config = pigeonVar_list[1] as AbrConfigMessage
      return SetAbrConfigRequest(playerId, config)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      playerId,
      config,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DecoderInfoMessage (
  val isHardwareAccelerated: Boolean,
  val decoderName: String? = null,
  val codec: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DecoderInfoMessage {
      val isHardwareAccelerated = pigeonVar_list[0] as Boolean
      val decoderName = pigeonVar_list[1] as String?
      val codec = pigeonVar_list[2] as String?
      return DecoderInfoMessage(isHardwareAccelerated, decoderName, codec)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isHardwareAccelerated,
      decoderName,
      codec,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SourceType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoSourceMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaMetadataMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EnterPipRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaMetadataRequest.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AbrConfigMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SetAbrConfigRequest.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DecoderInfoMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SourceType -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is VideoSourceMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is MediaMetadataMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is EnterPipRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is MediaMetadataRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is AbrConfigMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is SetAbrConfigRequest -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is DecoderInfoMessage -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AvPlayerHostApi {
  fun create(source: VideoSourceMessage, callback: (Result<Long>) -> Unit)
  fun dispose(playerId: Long, callback: (Result<Unit>) -> Unit)
  fun play(playerId: Long, callback: (Result<Unit>) -> Unit)
  fun pause(playerId: Long, callback: (Result<Unit>) -> Unit)
  fun seekTo(playerId: Long, positionMs: Long, callback: (Result<Unit>) -> Unit)
  fun setPlaybackSpeed(playerId: Long, speed: Double, callback: (Result<Unit>) -> Unit)
  fun setLooping(playerId: Long, looping: Boolean, callback: (Result<Unit>) -> Unit)
  fun setVolume(playerId: Long, volume: Double, callback: (Result<Unit>) -> Unit)
  fun isPipAvailable(callback: (Result<Boolean>) -> Unit)
  fun enterPip(request: EnterPipRequest, callback: (Result<Unit>) -> Unit)
  fun exitPip(playerId: Long, callback: (Result<Unit>) -> Unit)
  fun setMediaMetadata(request: MediaMetadataRequest, callback: (Result<Unit>) -> Unit)
  fun setNotificationEnabled(playerId: Long, enabled: Boolean, callback: (Result<Unit>) -> Unit)
  fun setSystemVolume(volume: Double, callback: (Result<Unit>) -> Unit)
  fun getSystemVolume(callback: (Result<Double>) -> Unit)
  fun setScreenBrightness(brightness: Double, callback: (Result<Unit>) -> Unit)
  fun getScreenBrightness(callback: (Result<Double>) -> Unit)
  fun setWakelock(enabled: Boolean, callback: (Result<Unit>) -> Unit)
  fun setAbrConfig(request: SetAbrConfigRequest, callback: (Result<Unit>) -> Unit)
  fun getDecoderInfo(playerId: Long, callback: (Result<DecoderInfoMessage>) -> Unit)

  companion object {
    /** The codec used by AvPlayerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `AvPlayerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AvPlayerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.create$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceArg = args[0] as VideoSourceMessage
            api.create(sourceArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            api.dispose(playerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            api.play(playerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            api.pause(playerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.seekTo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val positionMsArg = args[1] as Long
            api.seekTo(playerIdArg, positionMsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.setPlaybackSpeed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val speedArg = args[1] as Double
            api.setPlaybackSpeed(playerIdArg, speedArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.setLooping$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val loopingArg = args[1] as Boolean
            api.setLooping(playerIdArg, loopingArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.setVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val volumeArg = args[1] as Double
            api.setVolume(playerIdArg, volumeArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.isPipAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isPipAvailable{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.enterPip$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as EnterPipRequest
            api.enterPip(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.exitPip$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            api.exitPip(playerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.setMediaMetadata$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as MediaMetadataRequest
            api.setMediaMetadata(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.setNotificationEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val enabledArg = args[1] as Boolean
            api.setNotificationEnabled(playerIdArg, enabledArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.setSystemVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val volumeArg = args[0] as Double
            api.setSystemVolume(volumeArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.getSystemVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getSystemVolume{ result: Result<Double> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.setScreenBrightness$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val brightnessArg = args[0] as Double
            api.setScreenBrightness(brightnessArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.getScreenBrightness$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getScreenBrightness{ result: Result<Double> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.setWakelock$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            api.setWakelock(enabledArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.setAbrConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SetAbrConfigRequest
            api.setAbrConfig(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.av_player.AvPlayerHostApi.getDecoderInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            api.getDecoderInfo(playerIdArg) { result: Result<DecoderInfoMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
