// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * AvPlayerSourceType:
 * AV_PLAYER_SOURCE_TYPE_NETWORK:
 * AV_PLAYER_SOURCE_TYPE_ASSET:
 * AV_PLAYER_SOURCE_TYPE_FILE:
 *
 */
typedef enum {
  AV_PLAYER_SOURCE_TYPE_NETWORK = 0,
  AV_PLAYER_SOURCE_TYPE_ASSET = 1,
  AV_PLAYER_SOURCE_TYPE_FILE = 2
} AvPlayerSourceType;

/**
 * AvPlayerVideoSourceMessage:
 *
 */

G_DECLARE_FINAL_TYPE(AvPlayerVideoSourceMessage, av_player_video_source_message, AV_PLAYER, VIDEO_SOURCE_MESSAGE, GObject)

/**
 * av_player_video_source_message_new:
 * type_: field in this object.
 * url: field in this object.
 * headers: field in this object.
 * asset_path: field in this object.
 * file_path: field in this object.
 *
 * Creates a new #VideoSourceMessage object.
 *
 * Returns: a new #AvPlayerVideoSourceMessage
 */
AvPlayerVideoSourceMessage* av_player_video_source_message_new(AvPlayerSourceType type_, const gchar* url, FlValue* headers, const gchar* asset_path, const gchar* file_path);

/**
 * av_player_video_source_message_get_type_
 * @object: a #AvPlayerVideoSourceMessage.
 *
 * Gets the value of the type field of @object.
 *
 * Returns: the field value.
 */
AvPlayerSourceType av_player_video_source_message_get_type_(AvPlayerVideoSourceMessage* object);

/**
 * av_player_video_source_message_get_url
 * @object: a #AvPlayerVideoSourceMessage.
 *
 * Gets the value of the url field of @object.
 *
 * Returns: the field value.
 */
const gchar* av_player_video_source_message_get_url(AvPlayerVideoSourceMessage* object);

/**
 * av_player_video_source_message_get_headers
 * @object: a #AvPlayerVideoSourceMessage.
 *
 * Gets the value of the headers field of @object.
 *
 * Returns: the field value.
 */
FlValue* av_player_video_source_message_get_headers(AvPlayerVideoSourceMessage* object);

/**
 * av_player_video_source_message_get_asset_path
 * @object: a #AvPlayerVideoSourceMessage.
 *
 * Gets the value of the assetPath field of @object.
 *
 * Returns: the field value.
 */
const gchar* av_player_video_source_message_get_asset_path(AvPlayerVideoSourceMessage* object);

/**
 * av_player_video_source_message_get_file_path
 * @object: a #AvPlayerVideoSourceMessage.
 *
 * Gets the value of the filePath field of @object.
 *
 * Returns: the field value.
 */
const gchar* av_player_video_source_message_get_file_path(AvPlayerVideoSourceMessage* object);

/**
 * AvPlayerMediaMetadataMessage:
 *
 */

G_DECLARE_FINAL_TYPE(AvPlayerMediaMetadataMessage, av_player_media_metadata_message, AV_PLAYER, MEDIA_METADATA_MESSAGE, GObject)

/**
 * av_player_media_metadata_message_new:
 * title: field in this object.
 * artist: field in this object.
 * album: field in this object.
 * artwork_url: field in this object.
 *
 * Creates a new #MediaMetadataMessage object.
 *
 * Returns: a new #AvPlayerMediaMetadataMessage
 */
AvPlayerMediaMetadataMessage* av_player_media_metadata_message_new(const gchar* title, const gchar* artist, const gchar* album, const gchar* artwork_url);

/**
 * av_player_media_metadata_message_get_title
 * @object: a #AvPlayerMediaMetadataMessage.
 *
 * Gets the value of the title field of @object.
 *
 * Returns: the field value.
 */
const gchar* av_player_media_metadata_message_get_title(AvPlayerMediaMetadataMessage* object);

/**
 * av_player_media_metadata_message_get_artist
 * @object: a #AvPlayerMediaMetadataMessage.
 *
 * Gets the value of the artist field of @object.
 *
 * Returns: the field value.
 */
const gchar* av_player_media_metadata_message_get_artist(AvPlayerMediaMetadataMessage* object);

/**
 * av_player_media_metadata_message_get_album
 * @object: a #AvPlayerMediaMetadataMessage.
 *
 * Gets the value of the album field of @object.
 *
 * Returns: the field value.
 */
const gchar* av_player_media_metadata_message_get_album(AvPlayerMediaMetadataMessage* object);

/**
 * av_player_media_metadata_message_get_artwork_url
 * @object: a #AvPlayerMediaMetadataMessage.
 *
 * Gets the value of the artworkUrl field of @object.
 *
 * Returns: the field value.
 */
const gchar* av_player_media_metadata_message_get_artwork_url(AvPlayerMediaMetadataMessage* object);

/**
 * AvPlayerEnterPipRequest:
 *
 */

G_DECLARE_FINAL_TYPE(AvPlayerEnterPipRequest, av_player_enter_pip_request, AV_PLAYER, ENTER_PIP_REQUEST, GObject)

/**
 * av_player_enter_pip_request_new:
 * player_id: field in this object.
 * aspect_ratio: field in this object.
 *
 * Creates a new #EnterPipRequest object.
 *
 * Returns: a new #AvPlayerEnterPipRequest
 */
AvPlayerEnterPipRequest* av_player_enter_pip_request_new(int64_t player_id, double* aspect_ratio);

/**
 * av_player_enter_pip_request_get_player_id
 * @object: a #AvPlayerEnterPipRequest.
 *
 * Gets the value of the playerId field of @object.
 *
 * Returns: the field value.
 */
int64_t av_player_enter_pip_request_get_player_id(AvPlayerEnterPipRequest* object);

/**
 * av_player_enter_pip_request_get_aspect_ratio
 * @object: a #AvPlayerEnterPipRequest.
 *
 * Gets the value of the aspectRatio field of @object.
 *
 * Returns: the field value.
 */
double* av_player_enter_pip_request_get_aspect_ratio(AvPlayerEnterPipRequest* object);

/**
 * AvPlayerMediaMetadataRequest:
 *
 */

G_DECLARE_FINAL_TYPE(AvPlayerMediaMetadataRequest, av_player_media_metadata_request, AV_PLAYER, MEDIA_METADATA_REQUEST, GObject)

/**
 * av_player_media_metadata_request_new:
 * player_id: field in this object.
 * metadata: field in this object.
 *
 * Creates a new #MediaMetadataRequest object.
 *
 * Returns: a new #AvPlayerMediaMetadataRequest
 */
AvPlayerMediaMetadataRequest* av_player_media_metadata_request_new(int64_t player_id, AvPlayerMediaMetadataMessage* metadata);

/**
 * av_player_media_metadata_request_get_player_id
 * @object: a #AvPlayerMediaMetadataRequest.
 *
 * Gets the value of the playerId field of @object.
 *
 * Returns: the field value.
 */
int64_t av_player_media_metadata_request_get_player_id(AvPlayerMediaMetadataRequest* object);

/**
 * av_player_media_metadata_request_get_metadata
 * @object: a #AvPlayerMediaMetadataRequest.
 *
 * Gets the value of the metadata field of @object.
 *
 * Returns: the field value.
 */
AvPlayerMediaMetadataMessage* av_player_media_metadata_request_get_metadata(AvPlayerMediaMetadataRequest* object);

/**
 * AvPlayerAbrConfigMessage:
 *
 */

G_DECLARE_FINAL_TYPE(AvPlayerAbrConfigMessage, av_player_abr_config_message, AV_PLAYER, ABR_CONFIG_MESSAGE, GObject)

/**
 * av_player_abr_config_message_new:
 * max_bitrate_bps: field in this object.
 * min_bitrate_bps: field in this object.
 * preferred_max_width: field in this object.
 * preferred_max_height: field in this object.
 *
 * Creates a new #AbrConfigMessage object.
 *
 * Returns: a new #AvPlayerAbrConfigMessage
 */
AvPlayerAbrConfigMessage* av_player_abr_config_message_new(int64_t* max_bitrate_bps, int64_t* min_bitrate_bps, int64_t* preferred_max_width, int64_t* preferred_max_height);

/**
 * av_player_abr_config_message_get_max_bitrate_bps
 * @object: a #AvPlayerAbrConfigMessage.
 *
 * Gets the value of the maxBitrateBps field of @object.
 *
 * Returns: the field value.
 */
int64_t* av_player_abr_config_message_get_max_bitrate_bps(AvPlayerAbrConfigMessage* object);

/**
 * av_player_abr_config_message_get_min_bitrate_bps
 * @object: a #AvPlayerAbrConfigMessage.
 *
 * Gets the value of the minBitrateBps field of @object.
 *
 * Returns: the field value.
 */
int64_t* av_player_abr_config_message_get_min_bitrate_bps(AvPlayerAbrConfigMessage* object);

/**
 * av_player_abr_config_message_get_preferred_max_width
 * @object: a #AvPlayerAbrConfigMessage.
 *
 * Gets the value of the preferredMaxWidth field of @object.
 *
 * Returns: the field value.
 */
int64_t* av_player_abr_config_message_get_preferred_max_width(AvPlayerAbrConfigMessage* object);

/**
 * av_player_abr_config_message_get_preferred_max_height
 * @object: a #AvPlayerAbrConfigMessage.
 *
 * Gets the value of the preferredMaxHeight field of @object.
 *
 * Returns: the field value.
 */
int64_t* av_player_abr_config_message_get_preferred_max_height(AvPlayerAbrConfigMessage* object);

/**
 * AvPlayerSetAbrConfigRequest:
 *
 */

G_DECLARE_FINAL_TYPE(AvPlayerSetAbrConfigRequest, av_player_set_abr_config_request, AV_PLAYER, SET_ABR_CONFIG_REQUEST, GObject)

/**
 * av_player_set_abr_config_request_new:
 * player_id: field in this object.
 * config: field in this object.
 *
 * Creates a new #SetAbrConfigRequest object.
 *
 * Returns: a new #AvPlayerSetAbrConfigRequest
 */
AvPlayerSetAbrConfigRequest* av_player_set_abr_config_request_new(int64_t player_id, AvPlayerAbrConfigMessage* config);

/**
 * av_player_set_abr_config_request_get_player_id
 * @object: a #AvPlayerSetAbrConfigRequest.
 *
 * Gets the value of the playerId field of @object.
 *
 * Returns: the field value.
 */
int64_t av_player_set_abr_config_request_get_player_id(AvPlayerSetAbrConfigRequest* object);

/**
 * av_player_set_abr_config_request_get_config
 * @object: a #AvPlayerSetAbrConfigRequest.
 *
 * Gets the value of the config field of @object.
 *
 * Returns: the field value.
 */
AvPlayerAbrConfigMessage* av_player_set_abr_config_request_get_config(AvPlayerSetAbrConfigRequest* object);

/**
 * AvPlayerDecoderInfoMessage:
 *
 */

G_DECLARE_FINAL_TYPE(AvPlayerDecoderInfoMessage, av_player_decoder_info_message, AV_PLAYER, DECODER_INFO_MESSAGE, GObject)

/**
 * av_player_decoder_info_message_new:
 * is_hardware_accelerated: field in this object.
 * decoder_name: field in this object.
 * codec: field in this object.
 *
 * Creates a new #DecoderInfoMessage object.
 *
 * Returns: a new #AvPlayerDecoderInfoMessage
 */
AvPlayerDecoderInfoMessage* av_player_decoder_info_message_new(gboolean is_hardware_accelerated, const gchar* decoder_name, const gchar* codec);

/**
 * av_player_decoder_info_message_get_is_hardware_accelerated
 * @object: a #AvPlayerDecoderInfoMessage.
 *
 * Gets the value of the isHardwareAccelerated field of @object.
 *
 * Returns: the field value.
 */
gboolean av_player_decoder_info_message_get_is_hardware_accelerated(AvPlayerDecoderInfoMessage* object);

/**
 * av_player_decoder_info_message_get_decoder_name
 * @object: a #AvPlayerDecoderInfoMessage.
 *
 * Gets the value of the decoderName field of @object.
 *
 * Returns: the field value.
 */
const gchar* av_player_decoder_info_message_get_decoder_name(AvPlayerDecoderInfoMessage* object);

/**
 * av_player_decoder_info_message_get_codec
 * @object: a #AvPlayerDecoderInfoMessage.
 *
 * Gets the value of the codec field of @object.
 *
 * Returns: the field value.
 */
const gchar* av_player_decoder_info_message_get_codec(AvPlayerDecoderInfoMessage* object);

G_DECLARE_FINAL_TYPE(AvPlayerMessageCodec, av_player_message_codec, AV_PLAYER, MESSAGE_CODEC, FlStandardMessageCodec)

G_DECLARE_FINAL_TYPE(AvPlayerAvPlayerHostApi, av_player_av_player_host_api, AV_PLAYER, AV_PLAYER_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(AvPlayerAvPlayerHostApiResponseHandle, av_player_av_player_host_api_response_handle, AV_PLAYER, AV_PLAYER_HOST_API_RESPONSE_HANDLE, GObject)

/**
 * AvPlayerAvPlayerHostApiVTable:
 *
 * Table of functions exposed by AvPlayerHostApi to be implemented by the API provider.
 */
typedef struct {
  void (*create)(AvPlayerVideoSourceMessage* source, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*dispose)(int64_t player_id, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*play)(int64_t player_id, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*pause)(int64_t player_id, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*seek_to)(int64_t player_id, int64_t position_ms, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_playback_speed)(int64_t player_id, double speed, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_looping)(int64_t player_id, gboolean looping, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_volume)(int64_t player_id, double volume, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*is_pip_available)(AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*enter_pip)(AvPlayerEnterPipRequest* request, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*exit_pip)(int64_t player_id, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_media_metadata)(AvPlayerMediaMetadataRequest* request, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_notification_enabled)(int64_t player_id, gboolean enabled, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_system_volume)(double volume, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*get_system_volume)(AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_screen_brightness)(double brightness, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*get_screen_brightness)(AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_wakelock)(gboolean enabled, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_abr_config)(AvPlayerSetAbrConfigRequest* request, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*get_decoder_info)(int64_t player_id, AvPlayerAvPlayerHostApiResponseHandle* response_handle, gpointer user_data);
} AvPlayerAvPlayerHostApiVTable;

/**
 * av_player_av_player_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the AvPlayerHostApi API.
 */
void av_player_av_player_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const AvPlayerAvPlayerHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * av_player_av_player_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the AvPlayerHostApi API.
 */
void av_player_av_player_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * av_player_av_player_host_api_respond_create:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AvPlayerHostApi.create. 
 */
void av_player_av_player_host_api_respond_create(AvPlayerAvPlayerHostApiResponseHandle* response_handle, int64_t return_value);

/**
 * av_player_av_player_host_api_respond_error_create:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.create. 
 */
void av_player_av_player_host_api_respond_error_create(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_dispose:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.dispose. 
 */
void av_player_av_player_host_api_respond_dispose(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_dispose:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.dispose. 
 */
void av_player_av_player_host_api_respond_error_dispose(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_play:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.play. 
 */
void av_player_av_player_host_api_respond_play(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_play:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.play. 
 */
void av_player_av_player_host_api_respond_error_play(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_pause:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.pause. 
 */
void av_player_av_player_host_api_respond_pause(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_pause:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.pause. 
 */
void av_player_av_player_host_api_respond_error_pause(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_seek_to:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.seekTo. 
 */
void av_player_av_player_host_api_respond_seek_to(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_seek_to:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.seekTo. 
 */
void av_player_av_player_host_api_respond_error_seek_to(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_set_playback_speed:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.setPlaybackSpeed. 
 */
void av_player_av_player_host_api_respond_set_playback_speed(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_set_playback_speed:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.setPlaybackSpeed. 
 */
void av_player_av_player_host_api_respond_error_set_playback_speed(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_set_looping:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.setLooping. 
 */
void av_player_av_player_host_api_respond_set_looping(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_set_looping:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.setLooping. 
 */
void av_player_av_player_host_api_respond_error_set_looping(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_set_volume:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.setVolume. 
 */
void av_player_av_player_host_api_respond_set_volume(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_set_volume:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.setVolume. 
 */
void av_player_av_player_host_api_respond_error_set_volume(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_is_pip_available:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AvPlayerHostApi.isPipAvailable. 
 */
void av_player_av_player_host_api_respond_is_pip_available(AvPlayerAvPlayerHostApiResponseHandle* response_handle, gboolean return_value);

/**
 * av_player_av_player_host_api_respond_error_is_pip_available:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.isPipAvailable. 
 */
void av_player_av_player_host_api_respond_error_is_pip_available(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_enter_pip:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.enterPip. 
 */
void av_player_av_player_host_api_respond_enter_pip(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_enter_pip:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.enterPip. 
 */
void av_player_av_player_host_api_respond_error_enter_pip(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_exit_pip:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.exitPip. 
 */
void av_player_av_player_host_api_respond_exit_pip(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_exit_pip:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.exitPip. 
 */
void av_player_av_player_host_api_respond_error_exit_pip(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_set_media_metadata:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.setMediaMetadata. 
 */
void av_player_av_player_host_api_respond_set_media_metadata(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_set_media_metadata:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.setMediaMetadata. 
 */
void av_player_av_player_host_api_respond_error_set_media_metadata(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_set_notification_enabled:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.setNotificationEnabled. 
 */
void av_player_av_player_host_api_respond_set_notification_enabled(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_set_notification_enabled:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.setNotificationEnabled. 
 */
void av_player_av_player_host_api_respond_error_set_notification_enabled(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_set_system_volume:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.setSystemVolume. 
 */
void av_player_av_player_host_api_respond_set_system_volume(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_set_system_volume:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.setSystemVolume. 
 */
void av_player_av_player_host_api_respond_error_set_system_volume(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_get_system_volume:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AvPlayerHostApi.getSystemVolume. 
 */
void av_player_av_player_host_api_respond_get_system_volume(AvPlayerAvPlayerHostApiResponseHandle* response_handle, double return_value);

/**
 * av_player_av_player_host_api_respond_error_get_system_volume:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.getSystemVolume. 
 */
void av_player_av_player_host_api_respond_error_get_system_volume(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_set_screen_brightness:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.setScreenBrightness. 
 */
void av_player_av_player_host_api_respond_set_screen_brightness(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_set_screen_brightness:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.setScreenBrightness. 
 */
void av_player_av_player_host_api_respond_error_set_screen_brightness(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_get_screen_brightness:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AvPlayerHostApi.getScreenBrightness. 
 */
void av_player_av_player_host_api_respond_get_screen_brightness(AvPlayerAvPlayerHostApiResponseHandle* response_handle, double return_value);

/**
 * av_player_av_player_host_api_respond_error_get_screen_brightness:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.getScreenBrightness. 
 */
void av_player_av_player_host_api_respond_error_get_screen_brightness(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_set_wakelock:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.setWakelock. 
 */
void av_player_av_player_host_api_respond_set_wakelock(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_set_wakelock:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.setWakelock. 
 */
void av_player_av_player_host_api_respond_error_set_wakelock(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_set_abr_config:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 *
 * Responds to AvPlayerHostApi.setAbrConfig. 
 */
void av_player_av_player_host_api_respond_set_abr_config(AvPlayerAvPlayerHostApiResponseHandle* response_handle);

/**
 * av_player_av_player_host_api_respond_error_set_abr_config:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.setAbrConfig. 
 */
void av_player_av_player_host_api_respond_error_set_abr_config(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * av_player_av_player_host_api_respond_get_decoder_info:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AvPlayerHostApi.getDecoderInfo. 
 */
void av_player_av_player_host_api_respond_get_decoder_info(AvPlayerAvPlayerHostApiResponseHandle* response_handle, AvPlayerDecoderInfoMessage* return_value);

/**
 * av_player_av_player_host_api_respond_error_get_decoder_info:
 * @response_handle: a #AvPlayerAvPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AvPlayerHostApi.getDecoderInfo. 
 */
void av_player_av_player_host_api_respond_error_get_decoder_info(AvPlayerAvPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
